"""add model user_tg

Revision ID: 2d485c3cb789
Revises: 737ab3912d7c
Create Date: 2025-12-16 22:33:55.993774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d485c3cb789'
down_revision: Union[str, Sequence[str], None] = '737ab3912d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_in_telegram',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_code', sa.String(length=50), nullable=False),
    sa.Column('user_tg_id', sa.String(length=255), nullable=False),
    sa.Column('user_in_site', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_in_site'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_in_telegram')
    # ### end Alembic commands ###
